### ISSUE TITLE
Move hooks out of constructor

### ISSUE THREAD

**Issue by NickGreen** [a8cteam51/plugin-autoupdate-filter#12]
We probably shouldn't add all of our hooks in the class constructors: https://carlalexander.ca/designing-class-wordpress-hooks/

Yet, we are doing that here: https://github.com/a8cteam51/plugin-autoupdate-filter/blob/6cea95ea8bd73e9933444a4814f00f3ee4deeeca/class-plugin-autoupdate-filter.php#L17-L35

**Comment by jessLundie** [comment]
Closed via #14
