### ISSUE TITLE
Delay updates

### ISSUE THREAD

**Issue by NickGreen** [a8cteam51/plugin-autoupdate-filter#32]
## Synopsis

Delay some autoupdates to mitigate downtime.

## Details

The thought here is to give plugin developers some time to fix any flawed releases. We want to choose a reasonable amount of time so that we keep our sites up to date, but still allow a small buffer of time to allow developers to ship fixes to bugged releases.

Some thoughts on how this might work:

- Wait 48 hours to update any major or minor releases
- If a point release goes out (suggesting a security or bug fix), and the current plugin is on the same major and minor release, then update right away.
- Have an array of specific plugins which wait 7 days before updating. These plugins might relate to ecommerce, or other sensitive areas that directly affect our partners in a major way.

**Comment by NickGreen** [comment]
One of the problems is that the object we have to work with in the `auto_update_plugin` filter doesn't include release date, so we may only have the option of delaying _from the moment we realize there's an update_.

@nate-allen brainstormed up some code to do this:
```PHP
private function handle_woocommerce_update( $update, $item ): bool {
	$last_attempt = get_option( 't51_woocommerce_update_last_attempt' );
	$current_time = current_time( 'timestamp' );

	// If no previous attempt, block and log the attempt.
	if ( ! $last_attempt ) {
		update_option( 't51_woocommerce_update_last_attempt', $current_time );

		return false;
	}

	// If a week hasn't passed, block the attempt.
	if ( $current_time - $last_attempt < WEEK_IN_SECONDS ) {
		return false;
	}

	// Enough time has passed, allow the update and delete the timestamp.
	delete_option( 't51_woocommerce_update_last_attempt' );

	return true;
}
```

**Comment by nate-allen** [comment]
@tiagonoronha mentioned we can get the last updated date by [hitting this endpoint](https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&slug=woocommerce). So we wouldn't need to save an option.

**Comment by NickGreen** [comment]
Working branch up here: https://github.com/a8cteam51/plugin-autoupdate-filter/compare/trunk...issue_32

**Comment by NickGreen** [comment]
Merged here: https://github.com/a8cteam51/plugin-autoupdate-filter/pull/33
