### ISSUE TITLE
Add null check for plugin_file

### ISSUE THREAD

**Issue by cagrimmett** [a8cteam51/plugin-autoupdate-filter#41]
Woo encountered this fatal error on a T51 site before and after installing WC 9.2 Beta.

`Uncaught TypeError: Plugin_Autoupdate_Filter_Helpers::has_delay_passed(): Argument #3 ($plugin_file) must be of type string, null given`

https://github.com/a8cteam51/plugin-autoupdate-filter/blob/923a3ccf448be10673c46b6970fcd35c0982c7f6/includes/class-plugin-autoupdate-filter-helpers.php#L33

The other two variables have checks, but this one does not. 

https://github.com/woocommerce/woocommerce/issues/50490

**Comment by ahegyes** [comment]
Closing since the issue was addressed.
