### ISSUE TITLE
Override Atomic platform supression of auto-update emails

### ISSUE THREAD

**Issue by NickGreen** [a8cteam51/plugin-autoupdate-filter#8]
https://github.com/a8cteam51/team51-dev-requests/issues/1974

**Comment by mdrovdahl** [comment]
@NickGreen can you please extend this to capture WP Core updates too? Ref, https://developer.wordpress.org/reference/hooks/auto_core_update_email/. I think we just need another filter on `auto_core_update_email` to match the plugin one...

More context here: https://a8c.slack.com/archives/C01M1J49Q75/p1684338666771209?thread_ts=1684268770.263689&cid=C01M1J49Q75

**Comment by NickGreen** [comment]
Sure. How about theme updates?

**Comment by mdrovdahl** [comment]
Good thinking- but, let's wait on theme updates for now.

**Comment by NickGreen** [comment]
@mdrovdahl  Sorry this took so long to get back to, but I have a question. Are you wanting to do both of these two things?

- Include core updates in the time/date restrictions
- Send the core update emails to concierge@

**Comment by NickGreen** [comment]
PR up here: https://github.com/a8cteam51/plugin-autoupdate-filter/pull/15

**Comment by NickGreen** [comment]
Closing with PR 15 merged. Can reopen if it doesn't catch the emails we need.
